### ISSUE TITLE
[Bug] Sorting by column arrow icon is opposite to actual sort order

### ISSUE THREAD

**Issue by tusharsaxena** [kstange/MerchantPlus#3]
A small bug report - when sorting by price column, the down arrow in the column header indicates that it is sorting in descending order, but the actual sorting happens in ascending order.

See screenshot [here](https://i.imgur.com/EoxAyHr.jpeg)

**Comment by kstange** [comment]
This seems to actually be the case for all columns.  Pretty easy fix.  Thanks for pointing it out!
