### ISSUE TITLE
Not respecting Blizzard hidden items in vendor

### ISSUE THREAD

**Issue by cbossaers** [kstange/MerchantPlus#9]
As can be seen in the screenshots (I did manually change the size to 400 for a more similar screen-space to the default shop) the addon seems to ignore Blizzard's tags for items that have already been acquired and should not be shown. There appears to be some code that verifies this, since the "collected" column exists, but ultimately doesn't propperly do it. Ensemble (groups of transmogs, basically full sets) and I would assume arsenals aren't verified at all.

For toys the https://warcraft.wiki.gg/wiki/API_PlayerHasToy function could be used
For mounts https://wowpedia.fandom.com/wiki/API_C_MountJournal.GetMountInfo (isCollected property)
For the other types I'm not sure how Blizzard manages the difference between transmog item vs equipment with uncollected appearance, but https://wowpedia.fandom.com/wiki/API_C_TransmogCollection.GetAppearanceSources seems like a good place to start.

Though I am a programmer, Lua is a bit out of my scope. I am nonetheless willing to help any way I can to implement this fix/feature.

![Captura de pantalla 2024-08-02 074745](https://github.com/user-attachments/assets/6df27303-03bf-41b2-a5fb-4ab6210066cc)
![Captura de pantalla 2024-08-02 074811](https://github.com/user-attachments/assets/9b7b766e-bc07-45a7-a00b-c7f62dbcfbd1)

**Comment by kstange** [comment]
I can't figure out how to reproduce this issue.  I have most of the mounts on this vendor but they are not hidden from my normal Merchant tab.  When Blizzard hides an item on the merchant that you already know it is completely removed from the inventory that addons can access.  I can't even tell that it was ever there at all.  This merchant does not seem to be set up for that behavior, though some Remix merchants are.

The code you are looking at which checks for collection status is for showing the optional collectable column.  It doesn't hide anything; it just shows a column indicating what you have.

Here's the mount merchant list without Merchant Plus loaded for me
![image](https://github.com/user-attachments/assets/ca14eb3a-4968-4138-9d9e-1995e6a5fcd0)

And with Merchant Plus (you can see the Collectable column showing I have these):
![image](https://github.com/user-attachments/assets/e93e5152-f7f7-4c9d-acb9-0cbe346ec02e)

And here is Class Apparel which I've fully emptied out:
![image](https://github.com/user-attachments/assets/b975afbc-1bcb-402f-bdc0-74ca99f9a5d4)

And with Merchant Plus again, showing an empty panel:
![image](https://github.com/user-attachments/assets/15d7c942-529f-42d4-970b-f8fad8035254)

The only thing I can figure is you have some other addon that's hiding items from the Merchant tab, but is of course not aware of Merchant Plus.  I *do* plan to add filtering support to Merchant Plus eventually, including based on the Collectable column, but I'm still trying to wrap my head around the UI for it.

If you can give me any more info to reproduce it, let me know and feel free to reopen this.

**Comment by kstange** [comment]
A little interesting note as well: Blizzard sets which special currencies appear on the bottom of the merchant window based on what currencies are used predominantly in the inventory of the merchant.  You can see the mount merchant you have open shows bronze, like mine does, which means it thinks there are items in that inventory that can be bought with bronze.  The second set of windows for the Class Apparel window shows only gold because there game doesn't think there's anything for sale that uses a special currency.
